name: build-and-test-linux
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kclvm-builder
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - run: echo "KCLVM_PYTHON3_HOME=/usr/local/python3.9/bin/python3.9" >> $GITHUB_ENV

      - run: go run ./cmds/kcl-go

      - run: go run ./cmds/kcl-go setup-kclvm -triple=ubuntu -outdir=${HOME}/.kclvm-go
      - run: echo "${HOME}/.kclvm-go/ubuntu/bin" >> $GITHUB_PATH

      - run: which kclvm || which python3
      - run: which kcl
      - run: kcl --version || true


      - run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
